name: DeepRefine
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - bioconda
  - pyg
  - salilab
dependencies:
  - python=3.8
  - pip=22.0.3
  - pytorch=1.10.0
  - cudatoolkit=11.3
  - numpy=1.20.3
  - scipy=1.7.1
  - pandas=1.3.4
  - requests=2.26.0
  - networkx=2.6.3
  - msms=2.6.1
  - pyg=2.0.4
  - modeller=10.2
  - pip:
      - -e .
      - -r docker/requirements.txt
